# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-19 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180519_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='content',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
