# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-19 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_message_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='receiver_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_id',
            field=models.IntegerField(),
        ),
    ]
